<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://ws.gx10000.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://ws.gx10000.com" xmlns:intf="http://ws.gx10000.com" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
</wsdl:definitions>
